### ISSUE TITLE
Cannot build project

### ISSUE THREAD

**Issue by tymalo** [Fewnity/Nintendo-DS-Nifi-Template#1]
Downloaded the project and put at the root of my C: drive.  Ran make from directory. Have the latest version of devkitpro installed

**C:\Nintendo-DS-Nifi-Template-main>make
main.c
linking Nintendo-DS-Nifi-Template-main.elf
c:/devkitpro/devkitarm/bin/../lib/gcc/arm-none-eabi/12.1.0/../../../../arm-none-eabi/bin/ld.exe: cannot find -lNE: No such file or directory
collect2.exe: error: ld returned 1 exit status
make[1]: *** [/opt/devkitpro/devkitARM/ds_rules:54: /c/Nintendo-DS-Nifi-Template-main/Nintendo-DS-Nifi-Template-main.elf] Error 1
make: *** [Makefile:116: build] Error 2**

Removing -lNE from line 59 allowed to build. What is the lNE lib and is it actually needed?

**Comment by Fewnity** [comment]
Oh, it's an error, I created this project with Nitro Engine's makefile template (a 3D/physics engine), I need to remove this

**Comment by Fewnity** [comment]
Fixed with the new commit, thanks.
[New commit](https://github.com/Fewnity/Nintendo-DS-Nifi-Template/commit/629a51901511d70b84cbc95d36dc2d19b113c93f)
